name: Demo CI tasks
on:
  push:
    branches:
      - main
      - develop 

jobs:
  build-backend-demo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Grant execute permission to mvnw
        working-directory: backend/demo
        run: chmod +x mvnw
      - name: Build with Maven
        working-directory: backend/demo
        run: ./mvnw --batch-mode --update-snapshots package

